### ISSUE TITLE
`cmake` does not always imply `enableParallelBuilding = true`

### ISSUE THREAD

**Issue by samuela** [jtojnar/nixpkgs-hammering#101]
This issue is resultant from the discussion in https://github.com/NixOS/nixpkgs/pull/118000. In the julia derivations, cmake is used but the build is still serial. Adding `enableParallelBuilding = true` to the derivation does make the builds go parallel but it also triggers the `unnecessary-parallel-building` warning.

**Comment by jtojnar** [comment]
We should probably limit it to when dontUseCmakeConfigure is not true and
configurePhase is not overridden.
