### ISSUE TITLE
enableParallelBuilding detected for libsForQt5.callPackage

### ISSUE THREAD

**Issue by SuperSandro2000** [jtojnar/nixpkgs-hammering#11]
```
When evaluating attribute ‘texstudio’:
warning: unnecessary-parallel-building
Meson, CMake and qmake already set `enableParallelBuilding = true` by default so it is not necessary.
Near /home/hotpi/.cache/nixpkgs-review/pr-107904/nixpkgs/pkgs/development/libraries/qt-5/mkDerivation.nix:25:5:

25 |     enableParallelBuilding = args.enableParallelBuilding or true;
|     ^
See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unnecessary-parallel-building.md
```

**Comment by jtojnar** [comment]
I think that line can be safely removed, both cmake and qmake turn it on by default and looks like https://github.com/NixOS/nixpkgs/commit/3729b775315953084a14fba0c9ebdf8ecbab8b69 just fixed disabled parallel builds without realizing that removing the line will have the same effect.

**Comment by jtojnar** [comment]
Alternately, we could add blacklist for rule–file combinations or ignore errors from different file than the main package expression. That would need better heuristic for finding the expression file.

**Comment by SuperSandro2000** [comment]
> ignore errors from different file than the main package expression

That would be great and I could automatically write this into the report.md of nixpkgs-review.

**Comment by jtojnar** [comment]
The Qt issue has been fixed in https://github.com/NixOS/nixpkgs/pull/108888.
