### ISSUE TITLE
maintainers check does not respect pantheon.maintainers

### ISSUE THREAD

**Issue by SuperSandro2000** [jtojnar/nixpkgs-hammering#119]
https://github.com/NixOS/nixpkgs/pull/130338#issuecomment-881224633

https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/pantheon/apps/elementary-music/default.nix#L107

**Comment by jtojnar** [comment]
Pantheon currently lacks maintainers: https://github.com/NixOS/nixpkgs/blob/d38d4e060b01ff330197a29149b230364599d646/pkgs/desktops/pantheon/default.nix#L26

It would be nice to be able to check for maintainers teams but not sire how to do that without breaking BC.

**Comment by jtojnar** [comment]
Pantheon now has maintainers. It probably is fine to continue reporting empty teams as if there were no maintainers anyway.
