### ISSUE TITLE
Add to nixpkgs

### ISSUE THREAD

**Issue by figsoda** [jtojnar/nixpkgs-hammering#122]
Any reason this is not in nixpkgs?

**Comment by jtojnar** [comment]
Initially, I was too lazy, especially since flakes make it really convenient to use it even outside nixpkgs.

And now we depend on naersk for the Rust part, which cannot be used in nixpkgs. It should be possible to use Nixpkgs’s Rust infrastructure in Nixpkgs but we would have to deal with plumbing it into the Python part and it is too much for me at the moment. (Porting the Python part to Rust would make it nicer.)

Also the project is currently not versioned.

**Comment by winterqt** [comment]
> And now we depend on naersk for the Rust part, which cannot be used in nixpkgs.

Somewhat off-topic question, but is there a technical reason why Naersk can't be used in Nixpkgs other than the fact that it's not used for any package in Nixpkgs? Like, could it theoretically be used if all packages were switched to it, or is there some limitation which prevents this? (I'm not proposing that we switch, I'm just curious if there's a reason we couldn't.)

**Comment by jtojnar** [comment]
@winterqt Naersk requires `Cargo.lock` and `Cargo.toml` files so we would either need to use IFD, which is [currently not allowed](https://github.com/NixOS/rfcs/pull/109) in Nixpkgs, or copy the files into Nixpkgs.

**Comment by jtojnar** [comment]
I think that just refers to this: https://github.com/nix-community/naersk/pull/4 Before having TOML parser in Nix, you needed IFD even just to load the dependency data.

Accessing local files does not require a derivation so it does not constitute IFD. But if you only have the TOML files inside FOD, you obviously cannot get around IFD for this kind of builder. That’s why in Nixpkgs you either commit the lockfile or wrap the whole dependency tree in a FOD.

If you have more questions, moving to Discourse or Matrix would probably be more suitable.

**Comment by mweinelt** [comment]
Naersk was removed in #134. Is there a chance to revisit the topic?

**Comment by figsoda** [comment]
I took a look at `flake.nix` and looks like the only thing that wouldn't work in nixpkgs would be this
https://github.com/jtojnar/nixpkgs-hammering/blob/1b038ef38fececb39b65a4cdfa7273ed9d9359b4/flake.nix#L34-L37

We can either manually keep a list in nixpkgs or change the logic nixpkgs-hammer uses, e.g. have it read from its libexec and symlink `${rust-checks}/bin` to `$out/libexec`

**Comment by jtojnar** [comment]
That logic does not really need to be done in eval time. Converting it to bash would make it only slightly uglier.

**Comment by figsoda** [comment]
https://github.com/NixOS/nixpkgs/pull/211958
