### ISSUE TITLE
More complex `patches` AST structures not necessarily handled well

### ISSUE THREAD

**Issue by rmcgibbo** [jtojnar/nixpkgs-hammering#23]
It looks like there are some more complicated `patches` structures (in terms of the AST) out there in the wild that will get incorrectly flagged as "warning: missing-patch-comment `patches` should be a list."

Example: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/numpy/default.nix#L55-L66:
```
buildPythonPackage rec {
  ...
  patches = [
    # For compatibility with newer pytest
    (fetchpatch {
      url = "https://github.com/numpy/numpy/commit/ba315034759fbf91c61bb55390edc86e7b2627f3.patch";
      sha256 = "F2P5q61CyhqsZfwkLmxb7A9YdE+43FXLbQkSjop2rVY=";
    })
  ] ++ lib.optionals python.hasDistutilsCxxPatch [
    # We patch cpython/distutils to fix https://bugs.python.org/issue1222585
    # Patching of numpy.distutils is needed to prevent it from undoing the
    # patch to distutils.
    ./numpy-distutils-C++.patch
  ];
}
```

Perhaps, if `patches` is not a list, we should just not throw a warning at all...

**Comment by rmcgibbo** [comment]
Looks like I need to fix this bug since @AndersonTorres encountered it "in the wild".

**Comment by jtojnar** [comment]
Hmm, would be nice if we could evaluate the patches attribute and then obtain the corresponding AST nodes for the list items. Need to check if it is possible to write a Nix plug-in for that.

- <https://github.com/NixOS/nix/blob/3edcb198e5db69d0e5771a161a33115033b74af5/src/libstore/globals.hh#L825-L842>
- <https://github.com/NixOS/nix/blob/57b935a8931fb59cdfe521357e76326d467a9a86/tests/plugins.sh>
- <https://github.com/NixOS/nix/blob/57b935a8931fb59cdfe521357e76326d467a9a86/tests/plugins/plugintest.cc>

**Comment by rmcgibbo** [comment]
I suppose that's one way to do it. I think the near-term solution is simply to skip the ast-check itself if the node is not of type `list`.

**Comment by jtojnar** [comment]
Sounds good.
