### ISSUE TITLE
unclear-gpl: value is a set while a list was expected

### ISSUE THREAD

**Issue by SuperSandro2000** [jtojnar/nixpkgs-hammering#3]
I run ``nix run -f https://github.com/jtojnar/nixpkgs-hammering/archive/master.tar.gz -c nixpkgs-hammer grex`` on https://github.com/NixOS/nixpkgs/pull/100173 and got the following error:

```
/tmp/tmp.XZSxdAtHoo
error: value is a set while a list was expected, at /nix/store/jpy86aabmfqrk4w8c2n2mcad4nvn4wgh-nixpkgs-hammer/overlays/unclear-gpl.nix:27:16
```

**Comment by jtojnar** [comment]
Thanks for reporting this.
