### ISSUE TITLE
attribute-ordering: false positive when attributes are on one line

### ISSUE THREAD

**Issue by wirew0rm** [jtojnar/nixpkgs-hammering#31]
When there are multiple attributes all on the same line using inherit, there are false positives:

```
The attribute “src” should preferably come before “version” attribute in the expression.

Near /home/wirew0rm/nixpkgs/pkgs/development/tools/scenebuilder/default.nix:78:10:
   |
78 |   inherit pname version src;
   |          ^
Near /home/wirew0rm/nixpkgs/pkgs/development/tools/scenebuilder/default.nix:78:10:
   |
78 |   inherit pname version src;
   |          ^
See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/attribute-ordering.md
```

If i put them on separate lines with an inherit each, it resolves the problem.

Also, the attribute names seem to be swapped in the exception message, contradicting the example in the linked markdown (happens also if i put them on separate lines).

Thanks for this nice tool, especially for irregular contributers like me it saves a lot of pull request iterations just getting up to speed with the most recent packaging changes. (y)

**Comment by jtojnar** [comment]
Thanks for reporting, should be fixed now.
