### ISSUE TITLE
False positive unused argument when used in lib.getBin

### ISSUE THREAD

**Issue by SuperSandro2000** [jtojnar/nixpkgs-hammering#45]
```
Unused argument: direnv.
Near pkgs/misc/vim-plugins/overrides.nix:74:3:

────────────────────
   |
74 | , direnv
   |   ^
────────────────────
```

```
direnv-vim = super.direnv-vim.overrideAttrs (oa: {                                                                                                                                     preFixup = oa.preFixup or "" + ''
   substituteInPlace $out/share/vim-plugins/direnv-vim/autoload/direnv.vim \
     --replace "let s:direnv_cmd = get(g:, 'direnv_cmd', 'direnv')" \
       "let s:direnv_cmd = get(g:, 'direnv_cmd', '${lib.getBin direnv}/bin/direnv')"
 '';
});
```

**Comment by jtojnar** [comment]
Hmm, I am unable to reproduce on https://github.com/NixOS/nixpkgs/commit/e0c050583f75e6f69857d05a0e1a33f174eba74b with `nix run github:jtojnar/nixpkgs-hammering vimPlugins.direnv-vim` (https://github.com/jtojnar/nixpkgs-hammering/commit/42c3450d467461e27d2dff92bb86f4878e4fe5c9). What attribute are you using?

**Comment by SuperSandro2000** [comment]
Ah sorry, should have included that.

I've used ``nixpkgs-hammer --exclude attribute-ordering --exclude explicit-phases vimPlugins.fzfWrapper``.

**Comment by jtojnar** [comment]
Looking at the code in nix-explorer, rnix does not seem to parse string interpolations:

![image](https://user-images.githubusercontent.com/705123/107868863-275dd300-6e88-11eb-9ad9-a09f0d393f7b.png)

**Comment by jtojnar** [comment]
But it does seem to parse them on smaller examples so it is weird.

**Comment by rmcgibbo** [comment]
Yeah -- I just made myself the simplest test test hoping to trigger it
```
{ stdenv
, foo
}:

stdenv.mkDerivation {
  name = "used-in-string";

  src = ../fixtures/make;
  key = "${foo}";
}
```

But here, the `foo` is picked up totally correctly an argument that's used.

I'm continuing to poke at it.

**Comment by jtojnar** [comment]
It looks like it might be interpreting `'$` as escape sequence (instead of `''$`.

**Comment by jtojnar** [comment]
Do we have the correct version https://github.com/nix-community/rnix-parser/commit/f232ef4860a51f869eefa8d792098c5b8ca875fb?

**Comment by rmcgibbo** [comment]
Nope, we don't. Looks like we're at rnix 0.7.2 and that's in 0.8.0

**Comment by rmcgibbo** [comment]
I'll have a PR in a minute. Good spot @jtojnar.

**Comment by rmcgibbo** [comment]
Thanks for flagging this one, @SuperSandro2000.
